### ISSUE TITLE
Typescript error Property 'message' does not exist on type when using`errors.myField.message` after upgrading to 7.7.1

### ISSUE THREAD

**Issue by anark** [react-hook-form/react-hook-form#5421]
**Describe the bug**
After upgrading from 7.7.0 to 7.7.1 I am getting a typescript error
`Property 'message' does not exist on type` when trying to display the error message of a nested object.  This did not give an error in 7.7.0.

**To Reproduce**

1. Go to https://codesandbox.io/s/jolly-bell-szqwf?file=/src/App.tsx
2. Notice the typescript error message at line 30 `property message does not exist`

**Codesandbox link (Required)**
https://codesandbox.io/s/jolly-bell-szqwf?file=/src/App.tsx

**Expected behavior**
There is no typescript error.  The error message seems to properly display so I would expect that that the types would reflect that the message property exists.

**Desktop (please complete the following information):**

- OS: Mac
- Browser Chrome
- Version Version 90.0.4430.212 (Official Build) (x86_64)

**Comment by bluebill1049** [comment]
hi @anark for nested object data, you should use [NestedvValue](https://react-hook-form.com/ts#NestedValue) type: https://codesandbox.io/s/crazy-haze-t02yh?file=/src/App.tsx

**Comment by anark** [comment]
Thanks @bluebill1049, strange that the error didn't show up in 7.7.0.

Thank you so much for the quick response, that looks like it works.

**Comment by sandves** [comment]
@bluebill1049 I also ran into this issue when upgrading to v7.

The example you provided does not solve my case where one of the properties in the form definition is an interface:
```typescript
interface IPerson {
  first: string;
  last: string;
}

type FormValues = {
  person: NestedValue<IPerson>;
};
```

This gives me the following compilation error: 
`Type 'IPerson' does not satisfy the constraint 'unknown[] | Record<string, unknown> | Map<unknown, unknown>'.
  Type 'IPerson' is not assignable to type 'Record<string, unknown>'.
    Index signature is missing in type 'IPerson'.`

**Codesandbox**: https://codesandbox.io/s/sweet-wave-pwwmr

If I define the form like this instead, the compiler does not complain about it.
```typescript
type FormValues = {
  person: IPerson;
};
```

But when I try to to reference the error message like this `errors.person?.message`, I get the same error as @anark :
`Property 'message' does not exist on type 'DeepMap<IPerson, FieldError>'.`

The only way I was able to solve this was by typecasting, `(errors.person as any)?.message`, but this is not a solution I am comfortable with.

What is the correct way to solve this type error?

**Comment by bluebill1049** [comment]
try with type instead of interface

```
type FormValues = {
  person: NestedValue<IPerson>;
};
```

**Comment by sandves** [comment]
That does seem to work. However, it does not solve my problem. I am using a custom form control component that uses a complex type for `value` and `onChange`. This type is defined as an interface by the custom form control component which I do not have control over.

I could declare a type that has the exact same properties as the interface, but then I would have to map back and forth in `onChange` and `value`, which seems cumbersome. It would also require manual work to reflect eventual changes to the interface.

Are there any reasons why `NestedValue` does not accept an interface as the generic type?

**Comment by JoshuaCS94** [comment]
Any update regarding this? `NestesValue` doesn't even accept native `File`... 😄 I'm stuck at trying to upload a **logo** file in TS but I can't figure out how to properly declare the type of such field
