### ISSUE TITLE
V7 Typescript issue - RC 7.0.0-rc.7 - useFieldArray append issue

### ISSUE THREAD

**Issue by wdfinch** [react-hook-form/react-hook-form#4499]
**Describe the bug**
After upgrading to 7.0.0-rc.7, I'm noticing a typescript error with `useFieldArray's` `append` method when using a generic type for our form values. My form values are valid and have not changed between versions. The error is:

```
Argument of type '{ name: string; }' is not assignable to parameter of type 'never[]'.
  Object literal may only specify known properties, and 'name' does not exist in type 'never[]'
```

It seems related to having nested objects present in the form values type along with a field array. If you remove some of the other objects, the error should go away. 

**To Reproduce**

1. Go to the sandbox
2. View the error the append method

**Codesandbox link (Required)**
https://codesandbox.io/s/interesting-edison-sbbpy?file=/src/App.tsx

**Expected behavior**
There should be no error as my form values are a valid type

**Screenshots**
![Screenshot from 2021-03-23 17-16-16](https://user-images.githubusercontent.com/36898266/112235266-83d8ae80-8bfb-11eb-852a-76894e7130b0.png)

**Comment by wdfinch** [comment]
I would also like to add that there is an associated issue with `fields.map` here as well. It appears that doing something like:

```
{fields.map((item) => (
  <div key={item.id}></div>
))}
```

will also throw a typescript error on `item.id` The error is:

`TS2339: Property 'id' does not exist on type 'never'.`

I've updated the [sandbox](https://codesandbox.io/s/interesting-edison-sbbpy?file=/src/App.tsx:1955-2022) above to show this error. 

![Screenshot from 2021-03-24 08-07-11](https://user-images.githubusercontent.com/36898266/112334055-5c73f700-8c78-11eb-9eaa-25daeabd189b.png)

**Comment by kotarella1110** [comment]
@wdfinch

If the `control` object is passed to `useFieldArray`, Generics is not required.

```ts
const { fields, append } = useFieldArray({
  name: TimeBlockFieldNames.ClosedDates,
  control
});
```

Also, if you use `enum` for the key of `FormValues`, you need to specify the Generics as follows:

```ts
const { fields, append } = useFieldArray<FormValues, TimeBlockFieldNames.ClosedDates>({
  name: TimeBlockFieldNames.ClosedDates,
  control
});

const { fields, append } = useFieldArray({
  name: TimeBlockFieldNames.ClosedDates,
  control
});
```

**Comment by wdfinch** [comment]
Hi, @kotarella1110 thanks for the reply. I tried both of the above and it seems that with both solutions I'm getting a new error when using `fields.map` to render the inputs. The error I'm getting is:

`Type instantiation is excessively deep and possibly infinite.ts(2589)`

I've update my sandbox to include you're fix:
https://codesandbox.io/s/interesting-edison-sbbpy?file=/src/App.tsx

![Screenshot from 2021-03-24 22-42-38](https://user-images.githubusercontent.com/36898266/112425043-a4cffb00-8cf2-11eb-9289-fa47c10c33de.png)

**Comment by kotarella1110** [comment]
@wdfinch I will fix it 👍

**Comment by bluebill1049** [comment]
> I'm experiencing a similar issue on `7.0.0` where my key is named `localId`, and I have an object that has `myProp` as a field.
> 
> When doing `fields.map` the type of `item` is correctly inferred (vscode works fine), but when compiling and running tests with jest, I get this error:
> 
> `TS2339: Property 'myProp' does not exist on type 'Record<"localId", string>'.` when accessing the property from `item.myProp` inside the `map` callback. It seems like the compiler loses the the first part of `FieldArray<TFieldValues, TFieldArrayName> & Record<TKeyName, string>;` from `FieldArrayWithId`.
> 
> Has anybody else seen this?

can you share a codesandbox?

**Comment by HelenMariia** [comment]
Hello! Why can't I just use `useFieldArray` as at the simple example from docs: 
```
const { fields, append } = useFieldArray({
    control,
    name: "test"
  });
```
  The value which I pass to the `name` is not assignable to type 'never'. Did I miss something important ? 
  My version is: 7.19.1

**Comment by vghgergely** [comment]
> HelenMariia

Hi! You have probably found a way to at least work around this issue, but since this is the most fitting result on Google and I had the same problem now, I figured I might as well put the solution here.

My issue was that I have provided a generic interface to useFieldArray and it didn't have a property on it that was named "test".  The following would make your pasted code work:

```
interface TestInterface { 
  test: any
}

const { fields, append } = useFieldArray<TestInterface>({
  control,
  name: "test"
});
```

**Comment by Moshyfawn** [comment]
Please, upgrade to the latest version and see if the issue still persists.

**Comment by Moshyfawn** [comment]
> > I'm experiencing a similar issue on `7.0.0` where my key is named `localId`, and I have an object that has `myProp` as a field.
> > When doing `fields.map` the type of `item` is correctly inferred (vscode works fine), but when compiling and running tests with jest, I get this error:
> > `TS2339: Property 'myProp' does not exist on type 'Record<"localId", string>'.` when accessing the property from `item.myProp` inside the `map` callback. It seems like the compiler loses the the first part of `FieldArray<TFieldValues, TFieldArrayName> & Record<TKeyName, string>;` from `FieldArrayWithId`.
> > Has anybody else seen this?
> 
> @aecorredor did you ever find a solution to this? I'm having the exact same issue

Please, upgrade to the latest version and see if the issue still persists.

**Comment by dsauerbrun** [comment]
> > > I'm experiencing a similar issue on `7.0.0` where my key is named `localId`, and I have an object that has `myProp` as a field.
> > > When doing `fields.map` the type of `item` is correctly inferred (vscode works fine), but when compiling and running tests with jest, I get this error:
> > > `TS2339: Property 'myProp' does not exist on type 'Record<"localId", string>'.` when accessing the property from `item.myProp` inside the `map` callback. It seems like the compiler loses the the first part of `FieldArray<TFieldValues, TFieldArrayName> & Record<TKeyName, string>;` from `FieldArrayWithId`.
> > > Has anybody else seen this?
> > 
> > 
> > @aecorredor did you ever find a solution to this? I'm having the exact same issue
> 
> Please, upgrade to the latest version and see if the issue still persists.

@Moshyfawn I'm on 7.33.0
