### ISSUE TITLE
issue: Type instantiation is excessively deep and possibly infinite. after upgrading from v7.49.3

### ISSUE THREAD

**Issue by JounQin** [react-hook-form/react-hook-form#12817]
### Version Number

7.56.3

### Codesandbox/Expo snack

https://codesandbox.io/p/sandbox/prod-sunset-5nhdfw?file=%2Fsrc%2FApp.tsx%3A68%2C2

### Steps to reproduce

<img width="1629" alt="Image" src="https://github.com/user-attachments/assets/0c340b4e-d3d1-4196-95b0-9e51efde8528" />

### Expected behaviour

No error

### What browsers are you seeing the problem on?

Edge

### Relevant log output

```shell
Type instantiation is excessively deep and possibly infinite.typescript(2589)
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

---

It seems #11019 aims resolving the related issue, but no review afterwards and then closed by bot.

**Comment by gurobokum** [comment]
Today, I encountered the same error in `7.56.4`. Reverting back to `7.56.3` resolved it.
It just a simple zod schema

```typescript
const formSchema = z.object({
  apiToken: z.string().min(1, "API Token is required"),
});

type FormData = z.infer<typeof formSchema>;
...

  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm({
    resolver: zodResolver(formSchema),     // <- there is the error
  });


```

```bash
error TS2589: Type instantiation is excessively deep and possibly infinite.

43     resolver: zodResolver(formSchema),
                 ~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by JounQin** [comment]
@gurobokum Did you try v7.49.3 as I mentioned?

**Comment by colinhacks** [comment]
I believe this was due to some unfortunate type issues in some early versions of Zod 3.25. I recommend upgrading to Zod 4 or downgrading to Zod 3.25. In any case, this has been inactive for some type so seems like it's resolved itself.
