### ISSUE TITLE
issue: useController causing type error from 7.63.0 -> 7.64.0

### ISSUE THREAD

**Issue by sheuertz** [react-hook-form/react-hook-form#13081]
### Version Number

7.64.0

### Codesandbox/Expo snack

https://codesandbox.io/p/devbox/lucid-frost-gnfyfx

### Steps to reproduce

1. Run `tsc`
2. Receive error:
```
app/components/tree/tree.tsx:37:37 - error TS2322: Type 'string' is not assignable to type 'never'.

37   const { field } = useController({ name, defaultValue: [] });
                                       ~~~~

  node_modules/react-hook-form/dist/types/controller.d.ts:20:5
    20     name: TName;
           ~~~~
    The expected type comes from property 'name' which is declared here on type 'UseControllerProps<never[], never, never[]>'

app/components/tree/tree.tsx:37:43 - error TS2322: Type 'never[]' is not assignable to type 'undefined'.

37   const { field } = useController({ name, defaultValue: [] });
                                             ~~~~~~~~~~~~

  node_modules/react-hook-form/dist/types/controller.d.ts:23:5
    23     defaultValue?: FieldPathValue<TFieldValues, TName>;
           ~~~~~~~~~~~~
    The expected type comes from property 'defaultValue' which is declared here on type 'UseControllerProps<never[], never, never[]>'

app/components/tree/tree.tsx:46:26 - error TS2345: Argument of type 'string' is not assignable to parameter of type 'never'.

46       if (value.includes(itemId)) {
                            ~~~~~~

app/components/tree/tree.tsx:47:9 - error TS2322: Type 'string[]' is not assignable to type 'never[]'.
  Type 'string' is not assignable to type 'never'.

47         value = without(value, itemId);
           ~~~~~

app/components/tree/tree.tsx:49:20 - error TS2345: Argument of type 'string' is not assignable to parameter of type 'never'.

49         value.push(itemId);
```

### Expected behaviour

Expect no type errors on minor upgrade.

### Relevant log output

```shell

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by sheuertz** [comment]
I'm unable to get codesandbox to resolve with the latest versions of the various dependencies.

**Comment by lzlegg** [comment]
Yes, I also found this problem. Is the new version not forward compatible?

**Comment by httpete-broadcom** [comment]
Absolutely see this here with the latest version of ts and rhf.

**Comment by dbca-serkank** [comment]
this is breaking builds. don't we have transpiling checks? can we add it to the pipeline?

**Comment by bbarbosa85** [comment]
After upgrading to 7.64.0 or 7.65.0 the tsc command hangs and my project doesn't finish the build.
For some reason I get no output from tsc nor any errors.

Found that `react-hook-form` was the reason after upgrading package by package.
Using latest version of ts and react.

Problem lies on 7.64.0. 

7.63.0 works fine
