### ISSUE TITLE
Error after migrating to v4: Property 'message' does not exist on type 'FieldErrors[]'

### ISSUE THREAD

**Issue by cargallo** [react-hook-form/react-hook-form#728]
**Describe the bug**
I upgraded to v4 the code below throws this error: 

Property 'message' does not exist on type 'FieldError | FieldErrors<any> | FieldErrors<any>[]'.
  Property 'message' does not exist on type 'FieldErrors<any>[]'

```JSX
<Controller
  as={
	<TextField
	  fullWidth
	  required
	  variant="outlined"
	  margin="dense"
	  className={clsx(classes.textField)}
	  label="Nombre y Apellido"
	  error={!!errors.nombre}
	  helperText={errors.nombre && errors.nombre.message}
	/>
  }
  name="nombre"
  control={control}
/>
```

**Screenshots**
![image](https://user-images.githubusercontent.com/13320290/71529261-cb6e6e80-28c2-11ea-969c-b987fe9637f7.png)

**Comment by chriscarrillo** [comment]
I experienced something similar. The solution I found was the following:
```
const error = get(errors, name);
if(error && ('type' in error)) {
    // do something
}
```
The `get(...)` comes from [lodash](https://lodash.com/docs/4.17.15#get).

**Comment by cargallo** [comment]
Ok, here is an update. You need to pass an interface of your form data to useForm, but it still giving me an error on Date field. Anyway I think the best thing would be to allow the use without forcing to set the interface in useForm and let the developer decide using it or not.

```JSX
const methods = useForm<Operador>({ defaultValues: defaultValues, validationSchema: validationSchema });
```

![image](https://user-images.githubusercontent.com/13320290/71531925-acc2a480-28cf-11ea-8c59-02e7da6152ee.png)

**Comment by bluebill1049** [comment]
> Ok, here is an update. You need to pass an interface of your form data to useForm, but it still giving me an error on Date field. Anyway I think the best thing would be to allow the use without forcing to set the interface in useForm and let the developer decide using it or not.
> 
> ```js-jsx
> const methods = useForm<YourFormDataInterface>({ defaultValues: defaultValues, validationSchema: validationSchema });
> ```
> 
> ![image](https://user-images.githubusercontent.com/13320290/71531925-acc2a480-28cf-11ea-8c59-02e7da6152ee.png)

This looks like a double edge sword for me. I can either pick one side...  unless someone can show me how...

**Comment by bluebill1049** [comment]
May need your guys's help on this one: @stramel @barrymay

**Comment by cargallo** [comment]
I think this is possible I tried to follow the interfaces definition but not completly understanded them. Tomorrow will try again, if you have some documentation could be easier.

**Comment by longilineo** [comment]
I had to cast errors[fieldname] as any

`errors[fieldname] as any)?.message`

**Comment by bluebill1049** [comment]
any luck @cargallo ?

**Comment by nabc** [comment]
casting works, I did this: 
```
import { FieldError } from "react-hook-form";
{(errors[`${id}`]! as FieldError)!?.message}
```

**Comment by bluebill1049** [comment]
Hmmm i am feeling that V4 with nest errors (better TS support) at same time making your guy's life harder...

**Comment by bluebill1049** [comment]
If u guys have better solution to omit the type checking (as option), please feel free to submit PR.

**Comment by bluebill1049** [comment]
can some one provide a codesandbox with this issue? I could get it not crying about type if i don't supply type for useForm or `any`

**Comment by cargallo** [comment]
Hi @bluebill1049 here is a codesandbox (I don't know what's happening with type="date", it's not taking the value set in defaultValues) but hopefully it could be useful for this purpouse

**Comment by bluebill1049** [comment]
thansk @cargallo i will take a look today

**Comment by bluebill1049** [comment]
FYI: it should be a string type for the date input. still try to figure why there is issue using Date type tho.

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-typescript-error-idrxj

**Comment by pandaniell** [comment]
Faced this issue today where I wanted to create a input for a smart form component, using a formdata interface as a generic would work but since the formdata is unknown for a smart form input, passing in 
```typescript
const { errors } = useFormContext<Record<string, unknown>>();

<FormErrorMessage>{errors[name]?.message}</FormErrorMessage>
```works fine

**Comment by bluebill1049** [comment]
@pandaniell i think we have a ErrorMessage component now

**Comment by dimitir** [comment]
(errors.email as any)?.message it's work for me
