### ISSUE TITLE
watch not work in ios 10.2

### ISSUE THREAD

**Issue by fjson** [react-hook-form/react-hook-form#535]
```js
function Test() {
    const {
        register, watch,
    } = useForm({
        mode: 'onChange',
    });
    watch();
    return <input ref={register} name="test" />;
}
```

[Error] TypeError: Object.values is not a function. (In 'Object.values(fields)', 'Object.values' is undefined)
	getFieldsValues (react-hook-form.es.js:316)
	watch (react-hook-form.es.js:1444)
	Test (baseInfo.js:2407)
	renderWithHooks (react-dom.development.js:13354)
	mountIndeterminateComponent (react-dom.development.js:15407)
	performUnitOfWork (react-dom.development.js:20086)
	workLoop (react-dom.development.js:20127)
	callCallback (react-dom.development.js:147)
	dispatchEvent
	invokeGuardedCallbackDev (react-dom.development.js:196)
	invokeGuardedCallback (react-dom.development.js:250)
	replayUnitOfWork (react-dom.development.js:19310)
	renderRoot (react-dom.development.js:20240)
	performWorkOnRoot (react-dom.development.js:21164)
	performWork (react-dom.development.js:21074)
	performSyncWork (react-dom.development.js:21048)
	batchedUpdates$1 (react-dom.development.js:21275)
	runReactions (mobx.module.js:2200)
	endBatch (mobx.module.js:1846)
	_endAction (mobx.module.js:1135)
	executeAction (mobx.module.js:1082)
	onFulfilled (mobx.module.js:2793:93)
	promiseReactionJob

**Comment by bluebill1049** [comment]
This is not related to this lib. 

`[Error] TypeError: Object.values is not a function. ` most likely your transpile is not updated. or you can try to use the IE 11 version https://react-hook-form.com/faqs#BrowserSupport

**Comment by bluebill1049** [comment]
which react native version? or which version of `expo`?
