### ISSUE TITLE
[Bug]: Type error on error object if the field array shape is an interface

### ISSUE THREAD

**Issue by ymor** [react-hook-form/react-hook-form#6693]
### Version Number

7.16.2

### Codesandbox/Expo snack

https://codesandbox.io/s/property-name-does-not-exist-on-type-fielderror-vd6ei?file=/src/App.tsx

### Steps to reproduce

1. Go to https://codesandbox.io/s/property-name-does-not-exist-on-type-fielderror-vd6ei?file=/src/App.tsx
2. Scroll to the name input code
2. You can see typescript is complaining : `Property 'name' does not exist on type 'FieldError'`
3. If you scroll to the top and comment out the interface Person and use the type Person the error disappears

### Expected behaviour

Specifying the field array shape as an interface to work with typescript

### Relevant log output

```shell
Property 'name' does not exist on type 'FieldError'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kotarella1110** [comment]
@ymor To resolve #6523 issue, I have created #6605 PR.
fixed mapped types defined in interface to determine the field value.
Therefore, this is not a bug, but expected behavior.
Is there anything about this fix that is troubling you?

**Comment by bluebill1049** [comment]
thank you @kotarella1110 for the anwser.

**Comment by ymor** [comment]
@kotarella1110  No that's fine, thanks for the explanation. I guess the only thing I would say is that it could have being documented a bit better in the changelog :) Took me a while to work out what the issue was after the upgrade from 7.15.0.

**Comment by bluebill1049** [comment]
thanks @ymor i will get that done.
