### ISSUE TITLE
[Bug]: FieldState errors wrong typings

### ISSUE THREAD

**Issue by StampixSMO** [react-hook-form/react-hook-form#6653]
### Version Number

7.16.1

### Codesandbox/Expo snack

Latest version 7.16.1 does not seem to install on Codesandbox, see example repo instead

### Steps to reproduce

1. Clone example repo: https://github.com/StampixSMO/react-hook-form-fieldstate-errors-type
2. Install dependencies
3. Run `npm run compile`
4. Watch the TS error.

### Expected behaviour

The type of the errors object should not reflect the nested objects but only expose the `message` property.
This works fine in 7.15.4.

### Relevant log output

```
error TS2339: Property 'message' does
not exist on type 'DeepMap<DeepPartial<NestedValue<PhoneNumber>>, FieldError>'.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bluebill1049** [comment]
https://github.com/react-hook-form/react-hook-form/issues/2848

**Comment by StampixSMO** [comment]
@bluebill1049 Updated steps to reproduce that clearly indicate how to reproduce.

Cannot use CodeSandBox (see actual issue description please) as it doesn't allow me to install latest version (only up to 7.15.3).

Please re-open :)

**Comment by bluebill1049** [comment]
<img width="404" alt="Screen Shot 2021-09-28 at 9 35 19 am" src="https://user-images.githubusercontent.com/10513364/134999141-61d94cd3-7cce-4ebb-9f82-6b4725809162.png">

**Comment by StampixSMO** [comment]
@bluebill1049 I tried specifying it like that, but it doesn't install, seems like caches need to be updated or something?

See: https://codesandbox.io/s/naughty-glitter-yhtjl?file=/src/App.tsx
It won't install `react-hook-form` when you specify `7.16.1`

If you create a new sandbox and define it like your screenshot, it's not installing it. You can tell by looking up the `controller.d.ts` definition file, it's not the latest update from [`7.16.1`](https://github.com/react-hook-form/react-hook-form/blob/v7.16.1/src/types/controller.ts).
![image](https://user-images.githubusercontent.com/79153163/135042673-e96f563f-9862-4644-abac-38f5ba85558b.png)

Can't select it from the dropdown either.
![image](https://user-images.githubusercontent.com/79153163/135042558-e0b4484f-c844-4f34-b1de-e23add7b7c20.png)

**Comment by clothoo** [comment]
I tried the same in codesandbox. I can confirm it's not installed.
And I'm having the same problem as @StampixSMO 
![Screen Shot 2021-09-28 at 17 33 30](https://user-images.githubusercontent.com/3404581/135043426-bc4e72e4-9821-4a91-922d-f15435c98eea.png)

**Comment by bluebill1049** [comment]
thanks for the CSB and confirmation on the type issue.
