### ISSUE TITLE
Either data or error typings have to be wrong when using arrays

### ISSUE THREAD

**Issue by tomas-c** [react-hook-form/react-hook-form#953]
**Describe the bug**
When using useFieldArray, react-hook-form returns undefined when there are no fields. To handle this case the form data has to be typed as `type FormData = { arrayField: Field[] | undefined }`. This does not play well with typings for errors because the errors typings use `FormValues[Key] extends any[]` to decide if a field is an array ([here](https://github.com/react-hook-form/react-hook-form/blob/020a3729b320a46889f3dc9f1bbc7ecad7060002/src/types.ts#L116)).

**To Reproduce**
1. Clone https://github.com/tomas-c/react-hook-form-typescript-issue
2. Run `npm start`
3. Observe typescript errors

**Codesandbox link**
I could not find a sandbox that would typecheck using the latest typescript version. codesandbox.io for example seems to be locked to 3.6.2

**Additional context**
 - React hook form version 4.8.0
 - Typescript version 3.7.5

I propose to make useFieldArray return [] instead of undefined. This way the typings problem will be solved.

**Comment by bluebill1049** [comment]
I will investigate on this one.

**Comment by bluebill1049** [comment]
was looking at your git repo:

```
 const onSubmit = (data: FormData) => {
    console.log("data", data);

    // We cannot safely run the code below because
    // it can throw if there are no items in the array
    // because react-hook-form returns undefined as the field value
    // console.log("data", data.fieldArray.map(it => it));

    // And if we use "fieldArray?: FormFieldArray[];" 
    // or "fieldArray: FormFieldArray[] | undefined;"
    // then below doesn't work with typescript 3.7.5
    if (errors.fieldArray && errors.fieldArray.length) {
      console.log("error", errors.fieldArray[0].name);
    }
  };
```

you won't get the error object inside handleSubmit

**Comment by bluebill1049** [comment]
hey @stramel would you have any suggestion on this one? We definitely can't return empty array for errors, do you have any suggestion on changing our Type to support `[] | undefined`? 

thanks 
bill

**Comment by tomas-c** [comment]
> you won't get the error object inside handleSubmit

I put it inside the onSubmit so that `error.fieldArray` example would be close to the `data.fieldArray.map` example. In my actual app I'm doing `errors={errors?.fieldArray?.[index]?.name}` with Material UI's inputs.

**Comment by stramel** [comment]
I will take a look tomorrow when I'm at my computer

**Comment by bluebill1049** [comment]
Thanks a lot @stramel 🙏

**Comment by ian5484** [comment]
Is `useFieldArray` only for sets of fields?

I've got a multi select component which sets the value as an array items, eg: `[{ item: 1 }, { item: 2}]` or possibly just ids `[1,2,3,4]` -- not caring about user input on those items..

Taking select ids as the example... my interface would be...


```
selectedIds: Array<number>
```

But this gives TS Error on:

```
helperText={errors.selectedIds?.message}
```
```
Property 'message' does not exist on type 'FieldError[]'.ts(2339)
```

I want my `selectedIds` to be a single value which is an array, but typings for error messages seems to mold my decision into an field array for my error messages.

I might suggest exporting some typing specifically for FieldArray and leaving the array for my case?

**Comment by bluebill1049** [comment]
@stramel @kotarella1110 is this issue related to this as well: https://github.com/react-hook-form/react-hook-form/issues/987

**Comment by stramel** [comment]
Sorry for the delay in looking into this. Quickly created a sandbox to replicate what you had done. https://codesandbox.io/s/wonderful-payne-rlu2y

Reading through this issue now.

**Comment by stramel** [comment]
Okay, so this seems that you really have 2 parts to this issue.

1. `useFieldArray` is not correctly returning the default value of an empty array when specified in the `useForm` hook.

2. There is a quirk with our `FieldErrors` implementation that is causing form data properties that are `[] | undefined` to not properly be typed in the `errors` object. It has to do with the check we do `[] | undefined ` can't extend `any[]` so it ends up falling all the way down to `FieldError`. Simply marking that property required in the form data type does address the issue.

 @bluebill1049 I would mark both these as bugs but probably file them as separate issues for more clarity.

**Comment by bluebill1049** [comment]
thanks a lot for your investigation @stramel i have made a beta version to improve `[]` issue: react-hook-form@4.9.4-beta.1 (not TS related)

**Comment by bluebill1049** [comment]
the same issue as #987, let's focus on there.
