### ISSUE TITLE
issue: FieldArray type is unreachable from the package root -- shadowed by the new FieldArray component export (regression from #13394/#13596)

### ISSUE THREAD

**Issue by petergoldstein** [react-hook-form/react-hook-form#13618]
## Version Number

7.83.0 (latest as of writing; also reproduces on 7.82.0)

## Codesandbox/Expo snack

No sandbox — the repro is a pure type-only TypeScript issue with no runtime/browser component, so I've included a minimal, complete repro inline below instead. Happy to add a sandbox if that's still preferred.

## Steps to reproduce

`export type FieldArray<...>` (from `types/fieldArray.ts`) and the new `export const FieldArray` component (added in #13394 / v7.81.0, temporarily un-exported, restored in #13596 / v7.82.0) are both named `FieldArray`, and `src/index.ts` re-exports the component as a plain value:

```ts
// src/index.ts
export { FieldArray } from './fieldArray';   // <-- no `type` keyword
export * from './types';                     // <-- would otherwise surface `type FieldArray<...>`
```

Because it's an explicit named export, `export { FieldArray } from './fieldArray'` always wins over the `type FieldArray` pulled in transitively via `export * from './types'`. So at the package root, `FieldArray` can now only ever resolve to the component *value* — the pre-existing generic *type* is permanently shadowed and unreachable from `react-hook-form`'s root import path.

This breaks any consumer using the documented `FieldArray<TFieldValues, TFieldArrayName>` generic type (used for casting values passed to `update()`/`append()`/`insert()` on `useFieldArray`, per `UseFieldArrayAppend`/`UseFieldArrayInsert`'s own signatures, which still reference this type internally):

```ts
import { FieldArray, useFieldArray, type FieldValues, type ArrayPath } from "react-hook-form";

function Example<T extends FieldValues, N extends ArrayPath<T>>() {
  type ArrayItem = FieldArray<T, N>; // TS2749: 'FieldArray' refers to a value, but is being used as a type here. Did you mean 'typeof FieldArray'?
  const { update } = useFieldArray<T, N>({ name: undefined as never });
  const save = (value: unknown) => update(0, value as ArrayItem);
}
```

`tsc` (or any TS-aware editor) reports:

```
error TS2749: 'FieldArray' refers to a value, but is being used as a type here. Did you mean 'typeof FieldArray'?
```

Note `typeof FieldArray` is *not* a usable substitute — it resolves to the component's call signature `(props: FieldArrayProps<...>) => ReactElement`, not "one element of the field array," so it can't replace the original type in any of the call sites above without changing their meaning (I confirmed this produces further, different type errors when substituted).

## Expected behaviour

`FieldArray<TFieldValues, TFieldArrayName>` (the generic type) should remain importable from the package root alongside the new `FieldArray` component, without one shadowing the other — e.g. by exporting the type explicitly with `export type { FieldArray } from './types'` placed so it isn't shadowed, or by giving the component a distinct export name (as originally proposed in #13595 before #13596 was merged instead).

## Relevant log output

```
$ tsc --noEmit
error TS2749: 'FieldArray' refers to a value, but is being used as a type here. Did you mean 'typeof FieldArray'?
```

## Additional context

This was introduced by #13394 (FieldArray component) and made reachable again by #13596 (which restored the component export after #13595 flagged the exact same name collision and proposed renaming the component to `FieldArrayComponent` to avoid it — that alternative fix was not the one merged). The maintainer acknowledged the collision in review (["oh no... :("](https://github.com/react-hook-form/react-hook-form/pull/13595#issuecomment-4967993990)) but the merged fix (#13596) kept the component as `FieldArray` and renamed the *internal* type reference to `FieldArray_2` rather than resolving the public export collision, so the regression persists in every release since (verified still present in 7.83.0, the current latest).

**Comment by SaiprasadDash** [comment]
Hi! I'd like to work on this issue.

Since a maintainer already flagged the naming collision as a concern back in
#13595's review, before I open a PR I wanted to confirm which direction you'd
prefer:

1. Keep the component named `FieldArray` and fix the export shadowing with
   `export type { FieldArray } from './types'` (or equivalent), so the type
   is reachable again without any breaking change to the component's name.

2. Rename the component export (e.g. to `FieldArrayComponent`, as originally
   proposed in #13595) to avoid the collision at the source, if you'd rather
   resolve it that way even though it's a bit more disruptive.

Option 1 is non-breaking and can ship as a patch; option 2 would need a
major/minor bump depending on your versioning policy. Happy to implement
either — just want to align before writing the PR so I don't have to redo it.

I'll add a `.test-d.ts` type-level test to prevent this regression from
resurfacing in future exports, regardless of which direction we go.

**Comment by bluebill1049** [comment]
> Hi! I'd like to work on this issue.
> 
> Since a maintainer already flagged the naming collision as a concern back in [#13595](https://github.com/react-hook-form/react-hook-form/pull/13595)'s review, before I open a PR I wanted to confirm which direction you'd prefer:
> 
> 1. Keep the component named `FieldArray` and fix the export shadowing with
>    `export type { FieldArray } from './types'` (or equivalent), so the type
>    is reachable again without any breaking change to the component's name.
> 2. Rename the component export (e.g. to `FieldArrayComponent`, as originally
>    proposed in [fix new FieldArrayComponent and add export to index #13595](https://github.com/react-hook-form/react-hook-form/pull/13595)) to avoid the collision at the source, if you'd rather
>    resolve it that way even though it's a bit more disruptive.
> 
> Option 1 is non-breaking and can ship as a patch; option 2 would need a major/minor bump depending on your versioning policy. Happy to implement either — just want to align before writing the PR so I don't have to redo it.
> 
> I'll add a `.test-d.ts` type-level test to prevent this regression from resurfacing in future exports, regardless of which direction we go.

aha thanks i got a pr already will patch that soon.
